Making some texts configurable
alexishevia/rn-dropbox-filepicker pull request #5
Opened 2020-06-05 16:58 UTC by JOJ0

Hi, thanks for your patience, I was deeply involved in another project the last few weeks, but finally here is the PR we talked about.

I made the texts "strings" and not objects (as you suggested including eg <Text> tags as well) for the simple reason that I couldn't get it to work right away. Let's call this a draft.

all the best
Jojo

2020-06-06 14:51 UTC, alexishevia requested changes
You're heading in the right direction, but there's stuff missing to make this work.

You have to pass along the messages from Root to the sub-components.

In these 3 places:
- FileSelected
   ```
        <FileSelected
          filepath={filepath}
          openFilePicker={openFilePicker}
          onLogout={onLogout}
          fileSelectedMsg={fileSelectedMsg} // <-- this is what you need to add
        />
   ```
   https://github.com/alexishevia/rn-dropbox-filepicker/blob/master/lib/Root.js#L54-L58
- LoggedIn
   ```
   <LoggedIn 
     openFilePicker={openFilePicker}
     onLogout={onLogout}
     loggedInMsg={loggedInMsg} // <-- this is what you need to add 
   />;
   ```
   https://github.com/alexishevia/rn-dropbox-filepicker/blob/master/lib/Root.js#L62
- LoggedOut
   ```
   <LoggedOut 
     appKey={appKey} 
     onLogin={onLogin} 
     onError={onError}
     loggedOutMsg={loggedOutMsg} // <-- this is what you need to add 
    />
   ```
   https://github.com/alexishevia/rn-dropbox-filepicker/blob/master/lib/Root.js#L64

2020-06-06 14:51 UTC, alexishevia commented on lib/Root.js
> +  fileSeletctedMsg: 'You are connected to Dropbox and syncing to file:'
You have a typo here on the `fileSeletctedMsg` key. Should be `fileSelectedMsg`

2020-06-06 14:51 UTC, alexishevia commented on lib/Root.js
> +  fileSeletctedMsg: PropTypes.string.isRequired
Same typo here

2020-06-07 09:16 UTC, JOJ0 commented
Hi, sorry for forgetting this. I certainly had it when I coded/tested it in the project where I am actually using the FilePicker but forgot it when I put it in the freshly cloned FilePicker fork to send you the pull.

This happens if you don't test stuff..... :-/ I was to lazy to build a fresh rn project and put in the freshly adapted component. I am also not quite sure what would be the quickest workflow to create a dummy app, add the component (from local git) and code/test it. Started researching that right now.

One more thing: Will send you another commit soon. This also needs to be configurable to conclude this feature: https://github.com/alexishevia/rn-dropbox-filepicker/blob/master/lib/ChangeFileButton.js#L10

2020-06-07 10:01 UTC, JOJ0 commented
Well, I just learned that "yarn add" does understand any git repo urls and even local directories. That was too easy! Testing it right away issue solved...

2020-06-07 22:34 UTC, alexishevia commented on README.md
> +            fileSelectedMsg={fileSelectedMsg}
Do you mind adding the `fileChangeWarningMsg` to the README?

2020-06-07 22:48 UTC, alexishevia commented on README.md
> +            fileSelectedMsg={fileSelectedMsg}
Nevermind.. I'm creating a new PR to make it easier to contribute in the future. I'll add it there.

2020-06-07 22:49 UTC, alexishevia approved these changes
Thanks so much for this PR!

2020-06-07 22:50 UTC, merged

2020-06-08 06:04 UTC, JOJ0 commented
I have to thank you too! Learned a lot!